db:
  image: "postgres:9.4"
  ports:
    - "25432:5432"
  environment:
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
  volumes_from:
    - dbdata

dbdata:
  image: "postgres:9.4"
  volumes:
    - /var/lib/postgres
  command: "true"

web:
  build: "."
  environment:
    MIX_ENV: "prod"
  ports:
    - "4000:4000"
  links:
    - "db:db"
